[features]
hide = ["jackaudio-backend", "sdl-backend", "rodio-backend", "rodiojack-backend", "portaudio-backend", "gstreamer-backend", "passthrough-decoder", "pulseaudio-backend" ]

[[package.extra-patches]]
number = 10
file = "0001-switch-to-alsa-backend-by-default.patch"
comments = [ "Switch to using alsa backend by default" ]
